-- Movie Blog Posts Schema
-- Run this script in your Supabase SQL Editor to add blog post functionality

-- =====================================================
-- MOVIE BLOG POSTS TABLE
-- =====================================================

DROP TABLE IF EXISTS public.movie_blog_posts CASCADE;
CREATE TABLE IF NOT EXISTS public.movie_blog_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  movie_id BIGINT NOT NULL REFERENCES public.movies(id) ON DELETE CASCADE,
  slug TEXT NOT NULL UNIQUE, -- e.g., "inception-2010-johndoe"
  title TEXT NOT NULL,
  content TEXT, -- Generated HTML content
  meta_description TEXT,
  is_public BOOLEAN NOT NULL DEFAULT false, -- User privacy setting
  admin_approved BOOLEAN NOT NULL DEFAULT false, -- Admin can override
  view_count INTEGER NOT NULL DEFAULT 0,
  published_at TIMESTAMPTZ, -- When it was first made public
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, movie_id) -- One blog post per user per movie
);

-- =====================================================
-- INDEXES FOR PERFORMANCE
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_blog_posts_slug ON public.movie_blog_posts(slug);
CREATE INDEX IF NOT EXISTS idx_blog_posts_movie_id ON public.movie_blog_posts(movie_id);
CREATE INDEX IF NOT EXISTS idx_blog_posts_user_id ON public.movie_blog_posts(user_id);
CREATE INDEX IF NOT EXISTS idx_blog_posts_public ON public.movie_blog_posts(is_public, admin_approved);
CREATE INDEX IF NOT EXISTS idx_blog_posts_updated ON public.movie_blog_posts(updated_at DESC);

-- =====================================================
-- ROW LEVEL SECURITY (RLS)
-- =====================================================

ALTER TABLE public.movie_blog_posts ENABLE ROW LEVEL SECURITY;

-- Anyone can read public and admin-approved blog posts
DROP POLICY IF EXISTS "Anyone can view public blog posts" ON public.movie_blog_posts;
CREATE POLICY "Anyone can view public blog posts" ON public.movie_blog_posts
  FOR SELECT
  USING (
    (is_public = true AND admin_approved = true)
    OR user_id = auth.uid()
  );

-- Users can insert their own blog posts
DROP POLICY IF EXISTS "Users can create their own blog posts" ON public.movie_blog_posts;
CREATE POLICY "Users can create their own blog posts" ON public.movie_blog_posts
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Users can update their own blog posts
DROP POLICY IF EXISTS "Users can update their own blog posts" ON public.movie_blog_posts;
CREATE POLICY "Users can update their own blog posts" ON public.movie_blog_posts
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Users can delete their own blog posts
DROP POLICY IF EXISTS "Users can delete their own blog posts" ON public.movie_blog_posts;
CREATE POLICY "Users can delete their own blog posts" ON public.movie_blog_posts
  FOR DELETE
  USING (auth.uid() = user_id);

-- =====================================================
-- HELPER FUNCTIONS
-- =====================================================

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION public.handle_blog_post_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  
  -- Set published_at when post becomes public for the first time
  IF NEW.is_public = true AND OLD.is_public = false AND NEW.published_at IS NULL THEN
    NEW.published_at = NOW();
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to automatically update updated_at
DROP TRIGGER IF EXISTS trigger_blog_post_updated_at ON public.movie_blog_posts;
CREATE TRIGGER trigger_blog_post_updated_at
  BEFORE UPDATE ON public.movie_blog_posts
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_blog_post_updated_at();

-- =====================================================
-- VIEW: Public Blog Posts with Movie and User Data
-- =====================================================

DROP VIEW IF EXISTS public.public_blog_posts_view CASCADE;
CREATE VIEW public.public_blog_posts_view AS
SELECT 
  bp.id,
  bp.slug,
  bp.title,
  bp.content,
  bp.meta_description,
  bp.view_count,
  bp.published_at,
  bp.updated_at,
  bp.movie_id,
  bp.user_id,
  m.title AS movie_title,
  m.release_date,
  m.poster_url,
  m.director,
  m.runtime_minutes,
  m.genre,
  m.tmdb_id,
  m.imdb_id,
  m.overview,
  p.user_name,
  p.full_name,
  p.avatar_url
FROM public.movie_blog_posts bp
JOIN public.movies m ON bp.movie_id = m.id
LEFT JOIN public.profiles p ON bp.user_id = p.id
WHERE bp.is_public = true AND bp.admin_approved = true;

-- Grant access to the view
GRANT SELECT ON public.public_blog_posts_view TO anon, authenticated;

