-- =====================================================
-- CINEFIND COMPLETE DATABASE SCHEMA
-- =====================================================
-- Version: 2.0 (with Blog Posts feature)
-- Last Updated: December 2024
-- 
-- Run this script in your Supabase SQL Editor to set up 
-- all required tables, indexes, RLS policies, and triggers.
--
-- IMPORTANT: Run this in a fresh database or drop existing
-- tables first to avoid conflicts.
-- =====================================================

-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =====================================================
-- TABLE 1: PROFILES
-- Extends auth.users with additional user information
-- =====================================================

DROP TABLE IF EXISTS public.profiles CASCADE;
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  user_name TEXT UNIQUE NOT NULL,
  full_name TEXT NOT NULL,
  avatar_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.profiles IS 'User profiles extending auth.users';
COMMENT ON COLUMN public.profiles.user_name IS 'Unique username for display';
COMMENT ON COLUMN public.profiles.avatar_url IS 'URL to user avatar image';

-- =====================================================
-- TABLE 2: MOVIES
-- Core movie catalog from TMDB
-- =====================================================

DROP TABLE IF EXISTS public.movies CASCADE;
CREATE TABLE public.movies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  release_date DATE,
  poster_url TEXT,
  genre TEXT,
  director TEXT,
  runtime_minutes INTEGER,
  imdb_id TEXT,
  tmdb_id INTEGER UNIQUE,
  overview TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.movies IS 'Core movie/TV show catalog from TMDB';
COMMENT ON COLUMN public.movies.tmdb_id IS 'The Movie Database unique identifier';
COMMENT ON COLUMN public.movies.overview IS 'TMDB overview/description';

-- =====================================================
-- TABLE 3: CATEGORIES
-- Admin-curated categories (e.g., Action, Drama, Comedy)
-- =====================================================

DROP TABLE IF EXISTS public.categories CASCADE;
CREATE TABLE public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  color TEXT NOT NULL DEFAULT '#3B82F6',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.categories IS 'Admin-curated movie categories';

-- =====================================================
-- TABLE 4: TAGS
-- Admin-curated tags (e.g., character, dialogue, plot)
-- =====================================================

DROP TABLE IF EXISTS public.tags CASCADE;
CREATE TABLE public.tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  color TEXT NOT NULL DEFAULT '#3B82F6',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.tags IS 'Admin-curated movie tags for SEO and filtering';

-- =====================================================
-- TABLE 5: USER_MOVIE_CATEGORIES
-- Junction table: Users assign categories to movies
-- =====================================================

DROP TABLE IF EXISTS public.user_movie_categories CASCADE;
CREATE TABLE public.user_movie_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  movie_id BIGINT NOT NULL REFERENCES public.movies(id) ON DELETE CASCADE,
  category_id BIGINT NOT NULL REFERENCES public.categories(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, movie_id, category_id)
);

COMMENT ON TABLE public.user_movie_categories IS 'User assignments of categories to movies';

-- =====================================================
-- TABLE 6: USER_MOVIE_TAGS
-- Junction table: Users assign tags to movies
-- =====================================================

DROP TABLE IF EXISTS public.user_movie_tags CASCADE;
CREATE TABLE public.user_movie_tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  movie_id BIGINT NOT NULL REFERENCES public.movies(id) ON DELETE CASCADE,
  tag_id BIGINT NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, movie_id, tag_id)
);

COMMENT ON TABLE public.user_movie_tags IS 'User assignments of tags to movies';

-- =====================================================
-- TABLE 7: USER_NOTES
-- User notes/reviews for movies
-- =====================================================

DROP TABLE IF EXISTS public.user_notes CASCADE;
CREATE TABLE public.user_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  movie_id BIGINT NOT NULL REFERENCES public.movies(id) ON DELETE CASCADE,
  content TEXT NOT NULL CHECK (char_length(content) <= 1000),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.user_notes IS 'User personal notes and reviews for movies';

-- =====================================================
-- TABLE 8: USER_TAGS (Custom User Tags)
-- User-created custom tags (different from admin tags)
-- =====================================================

DROP TABLE IF EXISTS public.user_tags CASCADE;
CREATE TABLE public.user_tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  movie_id BIGINT NOT NULL REFERENCES public.movies(id) ON DELETE CASCADE,
  tag_name TEXT NOT NULL CHECK (char_length(tag_name) <= 50),
  color TEXT DEFAULT '#3B82F6',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, movie_id, tag_name)
);

COMMENT ON TABLE public.user_tags IS 'Custom user-created tags for personal organization';

-- =====================================================
-- TABLE 9: MOVIE_BLOG_POSTS
-- SEO-friendly blog posts generated for movies
-- =====================================================

DROP TABLE IF EXISTS public.movie_blog_posts CASCADE;
CREATE TABLE public.movie_blog_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  movie_id BIGINT NOT NULL REFERENCES public.movies(id) ON DELETE CASCADE,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  content TEXT,
  meta_description TEXT,
  is_public BOOLEAN NOT NULL DEFAULT true,
  admin_approved BOOLEAN NOT NULL DEFAULT true,
  view_count INTEGER NOT NULL DEFAULT 0,
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, movie_id)
);

COMMENT ON TABLE public.movie_blog_posts IS 'SEO-friendly blog posts for movies';
COMMENT ON COLUMN public.movie_blog_posts.slug IS 'URL-friendly identifier (e.g., inception-2010-johndoe)';
COMMENT ON COLUMN public.movie_blog_posts.is_public IS 'User privacy setting';
COMMENT ON COLUMN public.movie_blog_posts.admin_approved IS 'Admin moderation status';

-- =====================================================
-- INDEXES FOR PERFORMANCE
-- =====================================================

-- Profiles indexes
CREATE INDEX IF NOT EXISTS idx_profiles_user_name ON public.profiles(user_name);

-- Movies indexes
CREATE INDEX IF NOT EXISTS idx_movies_title ON public.movies(title);
CREATE INDEX IF NOT EXISTS idx_movies_genre ON public.movies(genre);
CREATE INDEX IF NOT EXISTS idx_movies_release_date ON public.movies(release_date);
CREATE INDEX IF NOT EXISTS idx_movies_tmdb_id ON public.movies(tmdb_id);
CREATE INDEX IF NOT EXISTS idx_movies_search ON public.movies 
  USING gin(to_tsvector('english', title || ' ' || COALESCE(overview, '') || ' ' || COALESCE(description, '')));

-- Categories indexes
CREATE INDEX IF NOT EXISTS idx_categories_name ON public.categories(name);

-- Tags indexes
CREATE INDEX IF NOT EXISTS idx_tags_name ON public.tags(name);

-- User movie categories indexes
CREATE INDEX IF NOT EXISTS idx_user_movie_categories_user_id ON public.user_movie_categories(user_id);
CREATE INDEX IF NOT EXISTS idx_user_movie_categories_movie_id ON public.user_movie_categories(movie_id);
CREATE INDEX IF NOT EXISTS idx_user_movie_categories_category_id ON public.user_movie_categories(category_id);

-- User movie tags indexes
CREATE INDEX IF NOT EXISTS idx_user_movie_tags_user_id ON public.user_movie_tags(user_id);
CREATE INDEX IF NOT EXISTS idx_user_movie_tags_movie_id ON public.user_movie_tags(movie_id);
CREATE INDEX IF NOT EXISTS idx_user_movie_tags_tag_id ON public.user_movie_tags(tag_id);

-- User notes indexes
CREATE INDEX IF NOT EXISTS idx_user_notes_user_id ON public.user_notes(user_id);
CREATE INDEX IF NOT EXISTS idx_user_notes_movie_id ON public.user_notes(movie_id);
CREATE INDEX IF NOT EXISTS idx_user_notes_user_movie ON public.user_notes(user_id, movie_id);
CREATE INDEX IF NOT EXISTS idx_user_notes_created_at ON public.user_notes(created_at);

-- User tags indexes
CREATE INDEX IF NOT EXISTS idx_user_tags_user_id ON public.user_tags(user_id);
CREATE INDEX IF NOT EXISTS idx_user_tags_movie_id ON public.user_tags(movie_id);
CREATE INDEX IF NOT EXISTS idx_user_tags_user_movie ON public.user_tags(user_id, movie_id);

-- Blog posts indexes
CREATE INDEX IF NOT EXISTS idx_blog_posts_slug ON public.movie_blog_posts(slug);
CREATE INDEX IF NOT EXISTS idx_blog_posts_movie_id ON public.movie_blog_posts(movie_id);
CREATE INDEX IF NOT EXISTS idx_blog_posts_user_id ON public.movie_blog_posts(user_id);
CREATE INDEX IF NOT EXISTS idx_blog_posts_public ON public.movie_blog_posts(is_public, admin_approved);
CREATE INDEX IF NOT EXISTS idx_blog_posts_updated ON public.movie_blog_posts(updated_at DESC);

-- =====================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- =====================================================

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.movies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_movie_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_movie_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.movie_blog_posts ENABLE ROW LEVEL SECURITY;

-- =====================================================
-- PROFILES POLICIES
-- =====================================================

DROP POLICY IF EXISTS "profiles_select_all" ON public.profiles;
CREATE POLICY "profiles_select_all" ON public.profiles
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
CREATE POLICY "profiles_update_own" ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

DROP POLICY IF EXISTS "profiles_insert_own" ON public.profiles;
CREATE POLICY "profiles_insert_own" ON public.profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

-- =====================================================
-- MOVIES POLICIES (publicly readable)
-- =====================================================

DROP POLICY IF EXISTS "movies_select_all" ON public.movies;
CREATE POLICY "movies_select_all" ON public.movies
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "movies_insert_authenticated" ON public.movies;
CREATE POLICY "movies_insert_authenticated" ON public.movies
  FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "movies_update_authenticated" ON public.movies;
CREATE POLICY "movies_update_authenticated" ON public.movies
  FOR UPDATE USING (auth.uid() IS NOT NULL);

-- =====================================================
-- CATEGORIES POLICIES (readable by all, admin can modify)
-- =====================================================

DROP POLICY IF EXISTS "categories_select_all" ON public.categories;
CREATE POLICY "categories_select_all" ON public.categories
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "categories_admin_all" ON public.categories;
CREATE POLICY "categories_admin_all" ON public.categories
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM auth.users 
      WHERE auth.uid() = id 
      AND (email LIKE '%admin%' OR email = 'testuser02@email.com')
    )
  );

-- =====================================================
-- TAGS POLICIES (readable by all, admin can modify)
-- =====================================================

DROP POLICY IF EXISTS "tags_select_all" ON public.tags;
CREATE POLICY "tags_select_all" ON public.tags
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "tags_admin_all" ON public.tags;
CREATE POLICY "tags_admin_all" ON public.tags
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM auth.users 
      WHERE auth.uid() = id 
      AND (email LIKE '%admin%' OR email = 'testuser02@email.com')
    )
  );

-- =====================================================
-- USER_MOVIE_CATEGORIES POLICIES (users own data only)
-- =====================================================

DROP POLICY IF EXISTS "user_movie_categories_own" ON public.user_movie_categories;
CREATE POLICY "user_movie_categories_own" ON public.user_movie_categories
  FOR ALL USING (auth.uid() = user_id);

-- =====================================================
-- USER_MOVIE_TAGS POLICIES (users own data only)
-- =====================================================

DROP POLICY IF EXISTS "user_movie_tags_own" ON public.user_movie_tags;
CREATE POLICY "user_movie_tags_own" ON public.user_movie_tags
  FOR ALL USING (auth.uid() = user_id);

-- =====================================================
-- USER_NOTES POLICIES (users own data only)
-- =====================================================

DROP POLICY IF EXISTS "user_notes_own" ON public.user_notes;
CREATE POLICY "user_notes_own" ON public.user_notes
  FOR ALL USING (auth.uid() = user_id);

-- =====================================================
-- USER_TAGS POLICIES (users own data only)
-- =====================================================

DROP POLICY IF EXISTS "user_tags_self_access" ON public.user_tags;
CREATE POLICY "user_tags_self_access" ON public.user_tags
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- =====================================================
-- MOVIE_BLOG_POSTS POLICIES
-- =====================================================

DROP POLICY IF EXISTS "Anyone can view public blog posts" ON public.movie_blog_posts;
CREATE POLICY "Anyone can view public blog posts" ON public.movie_blog_posts
  FOR SELECT USING (
    (is_public = true AND admin_approved = true)
    OR user_id = auth.uid()
  );

DROP POLICY IF EXISTS "Users can create their own blog posts" ON public.movie_blog_posts;
CREATE POLICY "Users can create their own blog posts" ON public.movie_blog_posts
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own blog posts" ON public.movie_blog_posts;
CREATE POLICY "Users can update their own blog posts" ON public.movie_blog_posts
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own blog posts" ON public.movie_blog_posts;
CREATE POLICY "Users can delete their own blog posts" ON public.movie_blog_posts
  FOR DELETE USING (auth.uid() = user_id);

-- Admin can manage all blog posts
DROP POLICY IF EXISTS "Admin can manage all blog posts" ON public.movie_blog_posts;
CREATE POLICY "Admin can manage all blog posts" ON public.movie_blog_posts
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM auth.users 
      WHERE auth.uid() = id 
      AND (email LIKE '%admin%' OR email = 'testuser02@email.com')
    )
  );

-- =====================================================
-- FUNCTIONS
-- =====================================================

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Function to handle blog post updates with published_at logic
CREATE OR REPLACE FUNCTION public.handle_blog_post_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  
  -- Set published_at when post becomes public for the first time
  IF NEW.is_public = true AND OLD.is_public = false AND NEW.published_at IS NULL THEN
    NEW.published_at = NOW();
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Function to create user profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, user_name, full_name)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'user_name', 'user_' || substring(NEW.id::text, 1, 8)),
    COALESCE(NEW.raw_user_meta_data->>'full_name', 'New User')
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to get user's tags for a specific movie
CREATE OR REPLACE FUNCTION get_user_movie_tags(user_uuid UUID, movie_bigint BIGINT)
RETURNS TABLE (
  id BIGINT,
  tag_name TEXT,
  color TEXT,
  created_at TIMESTAMPTZ
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    ut.id,
    ut.tag_name,
    ut.color,
    ut.created_at
  FROM public.user_tags ut
  WHERE ut.user_id = user_uuid AND ut.movie_id = movie_bigint
  ORDER BY ut.created_at DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to get user's notes for a specific movie
CREATE OR REPLACE FUNCTION get_user_movie_notes(user_uuid UUID, movie_bigint BIGINT)
RETURNS TABLE (
  id BIGINT,
  content TEXT,
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    un.id,
    un.content,
    un.created_at,
    un.updated_at
  FROM public.user_notes un
  WHERE un.user_id = user_uuid AND un.movie_id = movie_bigint
  ORDER BY un.created_at DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- TRIGGERS
-- =====================================================

-- Profiles updated_at trigger
DROP TRIGGER IF EXISTS update_profiles_updated_at ON public.profiles;
CREATE TRIGGER update_profiles_updated_at
    BEFORE UPDATE ON public.profiles
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Movies updated_at trigger
DROP TRIGGER IF EXISTS update_movies_updated_at ON public.movies;
CREATE TRIGGER update_movies_updated_at
    BEFORE UPDATE ON public.movies
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Categories updated_at trigger
DROP TRIGGER IF EXISTS update_categories_updated_at ON public.categories;
CREATE TRIGGER update_categories_updated_at
    BEFORE UPDATE ON public.categories
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Tags updated_at trigger
DROP TRIGGER IF EXISTS update_tags_updated_at ON public.tags;
CREATE TRIGGER update_tags_updated_at
    BEFORE UPDATE ON public.tags
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- User notes updated_at trigger
DROP TRIGGER IF EXISTS update_user_notes_updated_at ON public.user_notes;
CREATE TRIGGER update_user_notes_updated_at
    BEFORE UPDATE ON public.user_notes
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Blog posts updated_at trigger (with published_at logic)
DROP TRIGGER IF EXISTS trigger_blog_post_updated_at ON public.movie_blog_posts;
CREATE TRIGGER trigger_blog_post_updated_at
    BEFORE UPDATE ON public.movie_blog_posts
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_blog_post_updated_at();

-- Auto profile creation on signup trigger
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- =====================================================
-- VIEWS
-- =====================================================

-- Public Blog Posts View (for SEO and public access)
DROP VIEW IF EXISTS public.public_blog_posts_view CASCADE;
CREATE VIEW public.public_blog_posts_view AS
SELECT 
  bp.id,
  bp.slug,
  bp.title,
  bp.content,
  bp.meta_description,
  bp.view_count,
  bp.published_at,
  bp.updated_at,
  bp.movie_id,
  bp.user_id,
  bp.is_public,
  bp.admin_approved,
  m.title AS movie_title,
  m.release_date,
  m.poster_url,
  m.director,
  m.runtime_minutes,
  m.genre,
  m.tmdb_id,
  m.imdb_id,
  m.overview,
  p.user_name,
  p.full_name,
  p.avatar_url
FROM public.movie_blog_posts bp
JOIN public.movies m ON bp.movie_id = m.id
LEFT JOIN public.profiles p ON bp.user_id = p.id
WHERE bp.is_public = true AND bp.admin_approved = true;

-- Grant access to the view
GRANT SELECT ON public.public_blog_posts_view TO anon, authenticated;

-- =====================================================
-- SAMPLE ADMIN DATA (Optional)
-- =====================================================

-- Sample Categories
INSERT INTO public.categories (name, description, color) VALUES
  ('Action', 'High-energy films with physical stunts and chases', '#EF4444'),
  ('Drama', 'Character-driven narratives with emotional depth', '#8B5CF6'),
  ('Comedy', 'Films designed to make audiences laugh', '#F59E0B'),
  ('Horror', 'Films designed to frighten and thrill', '#1F2937'),
  ('Sci-Fi', 'Science fiction and futuristic themes', '#06B6D4'),
  ('Documentary', 'Non-fiction films about real events', '#10B981')
ON CONFLICT (name) DO NOTHING;

-- Sample Tags
INSERT INTO public.tags (name, description, color) VALUES
  ('character', 'Strong character development and arcs', '#3B82F6'),
  ('dialogue', 'Notable or quotable dialogue', '#10B981'),
  ('plot', 'Complex or engaging plot structure', '#F59E0B'),
  ('cinematography', 'Outstanding visual composition', '#8B5CF6'),
  ('soundtrack', 'Memorable musical score', '#EC4899'),
  ('twist', 'Surprising plot twists', '#EF4444'),
  ('pacing', 'Well-paced narrative', '#06B6D4'),
  ('acting', 'Outstanding performances', '#F97316')
ON CONFLICT (name) DO NOTHING;

-- =====================================================
-- END OF SCHEMA
-- =====================================================

